version: '3.4'

services:
  app:
    container_name: nodemongoauthapi
    image: nodemongoauthapi
    build: .
    ports:
      - 3005:3000
    links:
      - mongo
  mongo:
    container_name: mongo
    image: "mongo"
    ports:
      - "27018:27017"